"""
report_generator.py — Final report text formatter (Action Layer).

Receives the raw LLM output and cleans / structures it into a
professional report string ready for PDF export or API return.
"""

import re
import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


def format_forecast_report(
    ticker: str,
    llm_result: Dict[str, Any],
    market_data: Dict[str, Any],
) -> str:
    """
    Produce a human-readable market forecast one-pager from LLM output.

    Args:
        ticker:      Stock symbol.
        llm_result:  Parsed JSON dict from the NVIDIA LLM.
        market_data: Dict containing price, market_cap, pe_ratio, etc.

    Returns:
        Formatted multi-line string suitable for logging or display.
    """
    price = market_data.get("current_price", "N/A")
    mkt_cap = market_data.get("market_cap", "N/A")
    pe = market_data.get("pe_ratio", "N/A")

    positives: List[str] = llm_result.get("positives", [])
    risks: List[str] = llm_result.get("risks", [])

    positives_text = "\n".join(f"  + {p}" for p in positives) or "  N/A"
    risks_text = "\n".join(f"  - r" for r in risks) or "  N/A"

    report = (
        f"{'='*60}\n"
        f"  MARKET FORECAST: {ticker}\n"
        f"{'='*60}\n\n"
        f"REAL-TIME SNAPSHOT\n"
        f"  Current Price : ₹{price}\n"
        f"  Market Cap    : ₹{mkt_cap}M\n"
        f"  P/E Ratio     : {pe}\n\n"
        f"SUMMARY\n"
        f"  {llm_result.get('summary', 'N/A')}\n\n"
        f"POSITIVE DRIVERS\n{positives_text}\n\n"
        f"RISK FACTORS\n{risks_text}\n\n"
        f"FORECAST\n"
        f"  Direction      : {llm_result.get('prediction', 'N/A')}\n"
        f"  Est. Movement  : {llm_result.get('estimated_movement', 'N/A')}\n"
        f"  Confidence     : {llm_result.get('confidence', 'N/A')}/100\n"
        f"{'='*60}\n"
    )
    return report


def format_annual_report(
    ticker: str,
    year: int,
    report_text: str,
) -> str:
    """
    Wrap the raw LLM-generated report text with a professional header/footer.

    Ensures the word count target (400–500) is logged.
    """
    word_count = len(report_text.split())
    logger.info("Annual report for %s (%d) — %d words", ticker, year, word_count)

    header = (
        f"{'='*60}\n"
        f"  ANNUAL EQUITY REPORT\n"
        f"  Company : {ticker}\n"
        f"  Fiscal Year : {year}\n"
        f"  Generated by FinRobot-NVIDIA\n"
        f"{'='*60}\n\n"
    )
    footer = (
        f"\n\n{'='*60}\n"
        f"  DISCLAIMER: This report was generated by an AI system and\n"
        f"  is for informational purposes only. It does not constitute\n"
        f"  investment advice or a solicitation to buy or sell securities.\n"
        f"{'='*60}\n"
        f"  Word Count: ~{word_count}\n"
    )
    return header + report_text.strip() + footer


def clean_llm_text(text: str) -> str:
    """
    Remove common LLM artefacts from prose output:
    - Markdown bold (**text**)
    - Markdown italic (*text*)
    - Multiple blank lines
    """
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()
