import logging
from typing import Dict, Any

from perception.stock_router import normalize_ticker, get_price_history
from brain.llm_engine import call_nvidia_llm_json

logger = logging.getLogger(__name__)

def generate_signal(ticker: str) -> Dict[str, Any]:
    """
    Fetches the latest OHLCV data, calculates simple SMA and RSI, and asks LLM for a signal.
    """
    try:
        # Normalize ticker (RELIANCE → RELIANCE.NS)
        ticker = normalize_ticker(ticker)

        # Fetch data via stock_router (handles Indian + US routing)
        history = get_price_history(ticker, days=30)

        # get_price_history returns dict with 'candles' for Indian, or None for US
        candles = []
        if history and isinstance(history, dict):
            candles = history.get("candles", [])
        elif history and isinstance(history, list):
            candles = history

        # If stock_router returned None (US stock), try Finnhub via yfinance fallback
        if not candles:
            try:
                from perception.yfinance_service import get_price_history as yf_history
                candles = yf_history(ticker, days=30)
            except Exception:
                pass

        if not candles:
            return {"signal": "HOLD", "confidence": 0, "reason": "Unable to fetch price data for analysis."}

        closes = [c["c"] for c in candles]
        latest_price = closes[-1]
        
        # Calculate SMA-10
        sma_10 = sum(closes[-10:]) / 10 if len(closes) >= 10 else latest_price
        
        # Very simple RSI
        gains = []
        losses = []
        for i in range(1, len(closes)):
            diff = closes[i] - closes[i-1]
            if diff >= 0:
                gains.append(diff)
            else:
                losses.append(abs(diff))
        
        avg_gain = sum(gains[-14:]) / 14 if len(gains) >= 14 else 0.001
        avg_loss = sum(losses[-14:]) / 14 if len(losses) >= 14 else 0.001
        
        if avg_loss == 0:
            rsi = 100
        else:
            rs = avg_gain / avg_loss
            rsi = 100 - (100 / (1 + rs))

        # Detect currency
        is_indian = ticker.upper().endswith(".NS") or ticker.upper().endswith(".BO")
        currency = "₹" if is_indian else "$"

        # Prompt LLM
        prompt = f"""
You are an expert quantitative trading algorithm.
Evaluate the following stock: {ticker}
Current Price: {currency}{latest_price:.2f}
10-Day SMA: {currency}{sma_10:.2f}
14-Day RSI: {rsi:.2f}

Provide a JSON trading signal exactly matching this schema:
{{
  "signal": "BUY" | "SELL" | "HOLD",
  "confidence": integer between 0 and 100,
  "reason": "1-2 sentence compelling technical reason."
}}
Output ONLY valid JSON.
"""
        response = call_nvidia_llm_json([{"role": "user", "content": prompt}], max_tokens=150)
        
        return {
            "signal": response.get("signal", "HOLD"),
            "confidence": response.get("confidence", 50),
            "reason": response.get("reason", "Analysis generated by FinRobot AI.")
        }
        
    except Exception as e:
        logger.error(f"Signal Generation Error: {e}")
        return {"signal": "HOLD", "confidence": 50, "reason": "Technical analysis temporarily unavailable."}

def generate_trading_signal(ticker: str) -> Dict[str, Any]:
    """
    Generates a trading signal with explicit entry, target, and stop_loss prices,
    along with trend, confidence, and reasons based on simple SMA logic.
    """
    try:
        # Normalize ticker
        ticker = normalize_ticker(ticker)

        # Fetch data via stock_router (handles Indian + US routing)
        history = get_price_history(ticker, days=30)

        candles = []
        if history and isinstance(history, dict):
            candles = history.get("candles", [])
        elif history and isinstance(history, list):
            candles = history

        if not candles:
            try:
                from perception.yfinance_service import get_price_history as yf_history
                candles = yf_history(ticker, days=30)
            except Exception:
                pass

        if not candles:
            return {
                "entry": 0, "target_min": 0, "target_max": 0, "stop_loss": 0,
                "trend": "Neutral", "confidence": 0,
                "reason": ["Unable to fetch price data for analysis."]
            }

        closes = [c["c"] for c in candles]
        latest_price = closes[-1]
        
        # Calculate SMA-10
        sma_10 = sum(closes[-10:]) / 10 if len(closes) >= 10 else latest_price
        
        # Determine Trend
        is_bullish = latest_price > sma_10
        trend = "Bullish" if is_bullish else "Bearish"
        
        # Calculate targets and stop loss (based on long position for simplicity, per user prompt)
        entry = latest_price
        target_min = entry * 1.01
        target_max = entry * 1.03
        stop_loss = entry * 0.98
        
        # Confidence between 50 and 75
        diff_pct = abs(latest_price - sma_10) / (sma_10 if sma_10 else 1)
        # diff_pct is usually 0.01 to 0.10. Let's scale it
        added_conf = min(int(diff_pct * 100 * 2), 25)
        confidence = 50 + added_conf
        
        reason = []
        if is_bullish:
            reason.append("Price above moving average")
            reason.append("Positive trend momentum")
        else:
            reason.append("Price below moving average")
            reason.append("Negative trend momentum")
            
        reason.append("Stable volatility")
        
        return {
            "entry": round(entry, 2),
            "target_min": round(target_min, 2),
            "target_max": round(target_max, 2),
            "stop_loss": round(stop_loss, 2),
            "trend": trend,
            "confidence": confidence,
            "reason": reason
        }

    except Exception as e:
        logger.error(f"New Signal Generation Error: {e}")
        return {
            "entry": 0, "target_min": 0, "target_max": 0, "stop_loss": 0,
            "trend": "Neutral", "confidence": 0,
            "reason": ["Technical analysis temporarily unavailable."]
        }
